server:
  port: 8080 # 服务端口

spring:
  application:
    name: freemarker
  mvc:
    static-path-pattern: /static/**
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0     #检查模板更新延迟时间，设置为0表示立即检查，正式环境设置为3600秒
      classic_compatible: true     #如果变量为null,转化为空字符串
      whitespace_stripping: true   #去掉多余的空格,非常有用
      locale: zh_CN????????????    #中国
      default_encoding: utf-8???   #编码utf8
      url_escaping_charset: utf-8? #url编码utf8
      date_format: yyyy-MM-dd???   #显示日期格式
      time_format: HH:mm:ss??????? #显示时间格式
      datetime_format: yyyy-MM-dd? #显示日期时间格式
      number_format: 0.####        #数字显示格式
      boolean_format: true,false   #布尔显示格式
      tag_syntax: auto_detect      #标签语法自动检测
    template-loader-path: classpath:/templates/
    suffix: .html
